import bcrypt from 'bcrypt';
import moment from 'moment';
import { ROLE, LANGUAGE } from '../constants.js';

const getEnUsersData = async () => {
  return [
    {
      publicName: 'Hamed',
      profileImage: 'q2a_demo1.png',
      about: 'Some descriptions about q2a_admin',
      theme: 'light',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Hamed@gmail.com',
      password: await bcrypt.hash('Hamed_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Hamid',
      profileImage: 'q2a_demo1.png',
      about: 'Some descriptions about demo1 user',
      theme: 'light',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Hamid@gmail.com',
      password: await bcrypt.hash('Hamid_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Mahsa',
      profileImage: 'q2a_demo2.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Mahsa@gmail.com',
      password: await bcrypt.hash('Mahsa_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Ali',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Ali@gmail.com',
      password: await bcrypt.hash('Ali_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Omid',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Omid@gmail.com',
      password: await bcrypt.hash('Omid_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Nadia',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Nadia@gmail.com',
      password: await bcrypt.hash('Nadia_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Sara',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Sara@gmail.com',
      password: await bcrypt.hash('Sara_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Mehdi',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Mehdi@gmail.com',
      password: await bcrypt.hash('Mehdi_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Nader',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Nader@gmail.com',
      password: await bcrypt.hash('Nader_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Hoda',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Hoda@gmail.com',
      password: await bcrypt.hash('Hoda_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Sanaz',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Sanaz@gmail.com',
      password: await bcrypt.hash('Sanaz_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Zahra',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Zahra@gmail.com',
      password: await bcrypt.hash('Zahra_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Mohammad',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Mohammad@gmail.com',
      password: await bcrypt.hash('Mohammad_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Abbas',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Abbas@gmail.com',
      password: await bcrypt.hash('Abbas_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Aysa',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Aysa@gmail.com',
      password: await bcrypt.hash('Aysa_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Maryam',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Maryam@gmail.com',
      password: await bcrypt.hash('Maryam_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Kamal',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Kamal@gmail.com',
      password: await bcrypt.hash('Kamal_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Reza',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Reza@gmail.com',
      password: await bcrypt.hash('Reza_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Negar',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Negar@gmail.com',
      password: await bcrypt.hash('Negar_password', 10),
      isEmailVerified: true,
    },
    {
      publicName: 'Hadi',
      profileImage: 'q2a_demo3.png',
      about: 'Some descriptions about demo2 user',
      theme: 'dark',
      role: ROLE.USER_CONFIRMED,
      score: 0,
      language: LANGUAGE.PERSIAN,
      email: 'Hadi@gmail.com',
      password: await bcrypt.hash('Hadi_password', 10),
      isEmailVerified: true,
    },
  ];
};

const generateNumber = async (min, max) => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};
const getDateAndTimeEnUsersData = async () => {
  let obj = {};
  const askDateMoment = moment(new Date(+new Date(2022, 0, 1) - Math.floor(Math.random() * 100000000000)));
  const askDate = askDateMoment.format();
  const day = await generateNumber(1, 3);
  const ans1DateMoment = askDateMoment.add(day, 'days');
  const ans1Date = ans1DateMoment.format();
  const day2 = await generateNumber(3, 30);
  const ans2DateMoment = ans1DateMoment.add(day2, 'days');
  const ans2Date = ans2DateMoment.format();
  const month = await generateNumber(1, 12);
  const ans3DateMoment = ans2DateMoment.add(day, 'days').add(month, 'months');
  obj = {
    askDate: moment(askDate),
    ans1: moment(ans1Date),
    ans2: moment(ans2Date),
    ans3: ans3DateMoment,
  };
  return obj;
};

export { getEnUsersData, getDateAndTimeEnUsersData };
